ARG GOLANG=golang:1.15.10-alpine3.12
FROM ${GOLANG} AS prepare
ARG ARCH
RUN apk --no-cache add \
    bash \
    ca-certificates \
    curl \
    gcc \
    git
COPY ./ /go/src/github.com/rancher/system-upgrade-controller/
WORKDIR /go/src/github.com/rancher/system-upgrade-controller
RUN chmod +x /go/src/github.com/rancher/system-upgrade-controller/scripts/*
FROM prepare AS build
RUN /go/src/github.com/rancher/system-upgrade-controller/scripts/entry build

FROM build AS validate
RUN GO111MODULE=on GOPROXY=direct go get golang.org/x/lint/golint@83fdc39ff7b56453e3793356bcff3070b9b96445
RUN GO111MODULE=on GOPROXY=direct go get golang.org/x/tools/cmd/goimports@gopls/v0.6.9
RUN curl -sL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.38.0
RUN /go/src/github.com/rancher/system-upgrade-controller/scripts/entry validate

FROM scratch
COPY --from=build /go/src/github.com/rancher/system-upgrade-controller/bin/ /bin/
ENTRYPOINT ["/bin/system-upgrade-controller"]
